/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/AdoptionSucess`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/DogAdopt`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/DogFilter`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/DogInfo`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/registro/registro`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/DogAdopt/AdoptionSucess`; params?: Router.UnknownOutputParams; } | { pathname: `/DogAdopt/DogAdopt`; params?: Router.UnknownOutputParams; } | { pathname: `/DogAdopt/DogFilter`; params?: Router.UnknownOutputParams; } | { pathname: `/DogAdopt/DogInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `/registro/registro`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/DogAdopt/AdoptionSucess${`?${string}` | `#${string}` | ''}` | `/DogAdopt/DogAdopt${`?${string}` | `#${string}` | ''}` | `/DogAdopt/DogFilter${`?${string}` | `#${string}` | ''}` | `/DogAdopt/DogInfo${`?${string}` | `#${string}` | ''}` | `/home/home${`?${string}` | `#${string}` | ''}` | `/login/login${`?${string}` | `#${string}` | ''}` | `/registro/registro${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/AdoptionSucess`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/DogAdopt`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/DogFilter`; params?: Router.UnknownInputParams; } | { pathname: `/DogAdopt/DogInfo`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/registro/registro`; params?: Router.UnknownInputParams; };
    }
  }
}
